Gp 3173 update build output to scratch
oicr-gsi/vidarr pull request #355
Opened 2024-02-14 17:00 UTC by Christopher-Ho

Added an optional output directory argument
- Allows user to choose output directory for test outputs
- This is an optional argument 
- Default behaviour is to output to tmp directory 

Jira ticket: https://jira.oicr.on.ca/browse/GP-3173

- [ X ] Includes a change file
- [ X ] Updates developer documentation

2024-02-14 17:14 UTC, avarsava requested changes
I am confused why these changes couldn't be limited to vidarr-tools? Could vidarr-tools not get the files from the temporary directory and move them to a user-specified location itself?

2024-02-14 17:14 UTC, avarsava commented on vidarr-cli/src/main/java/ca/on/oicr/gsi/vidarr/cli/TestValidatorScript.java
> +  {
Please revert style changes and refer to https://github.com/oicr-gsi/vidarr/blob/master/code-style.md

2024-02-14 17:14 UTC, avarsava commented on admin-guide.md
> +Users have an option to provide a directory filepath for the provisioned out file. If none is provided then
Please stick to 80 character lines.

2024-02-14 17:14 UTC, avarsava commented on changes/add_optional_output_directory_argument.md
> +Add an optional output directory argument
Please clarify that this is only for vidarr-cli

2024-02-15 13:57 UTC, grapigeau commented on vidarr-pluginapi/src/main/java/ca/on/oicr/gsi/vidarr/ConsumableResource.java
> +   * @param createdTime the time the workflow run was created
Looks like this commit might've been pulled in by accident?

2024-02-15 19:25 UTC, avarsava commented
1. Do not revert Andre's changes, that will destroy those changes when merged. Please rebase your branch on master.
2. Please address my question about why this change requires vidarr changes.

2024-02-20 14:31 UTC, closed without merging